//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int IdDocumento { get; set; }
        public System.DateTime fechaRadicado { get; set; }
        public System.DateTime fechaDocumento { get; set; }
        public System.DateTime fechaVence { get; set; }
        public string ubicacion { get; set; }
        public int Id_Persona { get; set; }
        public int Id_TipoDocumento { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual persona persona { get; set; }
        public virtual tipoDocumento tipoDocumento { get; set; }
    }
}
